name: Cypress E2E Tests

on:
  push:
    branches:
      - "main"
      - "test*"
  pull_request:
    branches:
      - "main"
      - "test*"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: marketplace
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_LIVE: "False"
      DATABASE_URL: postgres://postgres:password@localhost:5432/marketplace
      REACT_APP_API_URL: http://localhost:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Django dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r simpleRentals/requirements.txt

      - name: Run Django migrations
        run: |
          cd simpleRentals
          python manage.py migrate

      - name: Seed test data
        run: |
          cd simpleRentals
          python manage.py seed_test_data

      - name: Start Django server
        run: |
          cd simpleRentals
          python manage.py runserver [::]:8000 &
          echo $! > django_pid.txt
        shell: bash

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Create frontend .env file
        run: |
          cat <<EOF > frontend/.env
          VITE_API_URL=http://localhost:8000
          EOF

      - name: Start React frontend
        run: |
          cd frontend
          npm run dev &
          echo $! > react_pid.txt
        shell: bash

      - name: Wait for frontend and backend to be ready
        run: |
          echo "Waiting for Django..."
          until curl --output /dev/null --silent --head --fail http://localhost:8000; do
            sleep 2
          done
          echo "Waiting for React..."
          until curl --output /dev/null --silent --head --fail http://localhost:5173; do
            sleep 2
          done

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          start: echo "Already running"
          wait-on: "http://localhost:5173/"
          wait-on-timeout: 120
          command: npm run cypress:run

      - name: Upload Cypress Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: frontend/cypress/videos

      - name: Stop Django and React servers
        if: always()
        run: |
          kill $(cat django_pid.txt) || true
          kill $(cat react_pid.txt) || true
        shell: bash
