name: Django CI

on:
  push:
    branches:
      - "main"
      - "test*"
  pull_request:
    branches:
      - "main"
      - "test*"

jobs:
  build:

    runs-on: ubuntu-22.04  # Use stable runner

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: marketplace
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r simpleRentals/requirements.txt

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Run Django migrations
      run: |
        cd simpleRentals
        python manage.py migrate

    - name: Run Django tests
      run: |
        cd simpleRentals
        python manage.py test
